services:
  structurizr-lite:
    image: structurizr/lite
    container_name: structurizr-lite
    ports:
      - "8080:8080"
    volumes:
      - ./structurizr:/usr/local/structurizr
    restart: unless-stopped
