include:
  - compose.db.yml
  - compose.mq.yml
  - compose.apps.yml
  - compose.monitoring.yml
  - compose.tools.yml

networks:
  searc-network:
    driver: bridge

volumes:
  postgres_data:
  cleaner_postgres_data: