services:
  searc-postgres:
    image: postgres:latest
    container_name: searc-db
    hostname: searc-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - searc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  flyway:
    image: flyway/flyway:latest
    command: >
      migrate
    volumes:
      - ./sql/search:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://searc-db:${DB_PORT}/${DB_NAME}
      FLYWAY_USER: ${DB_USER}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
      FLYWAY_SCHEMAS: public
      FLYWAY_CONNECT_RETRIES: 50
    depends_on:
      searc-postgres:
        condition: service_healthy
    networks:
      - searc-network
